# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook
# yamllint enable rule:line-length
---
- name: Personal Ubuntu Environment
  hosts: localhost

  pre_tasks:
    - name: Stop if not Debian/Ubuntu
      ansible.builtin.fail:
        msg: This playbook is only for Ubuntu
      when: ansible_os_family != "Debian"

    - name: Update apt
      ansible.builtin.apt:
        update_cache: true
      become: true

  environment:
    DEBIAN_FRONTEND: noninteractive

  tasks:
    - name: APT
      ansible.builtin.import_tasks: tasks/apt.yml
      tags: apt
    - name: Dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yml
      tags: dotfiles
    - name: ZSH
      ansible.builtin.import_tasks: tasks/zsh.yml
      tags:
        - dotfiles
        - zsh
    - name: Fonts
      ansible.builtin.import_tasks: tasks/fonts.yml
      tags:
        - dotfiles
        - fonts
    - name: Python
      ansible.builtin.import_tasks: tasks/python.yml
      tags: python
    - name: Nodejs
      ansible.builtin.import_tasks: tasks/node.yml
      tags:
        - node
        - npm
    - name: Go
      ansible.builtin.import_tasks: tasks/go.yml
      tags: go
    - name: Rust
      ansible.builtin.import_tasks: tasks/rust.yml
      tags: rust
    - name: Neovim
      ansible.builtin.import_tasks: tasks/neovim.yml
      tags: neovim
    - name: Visual Studio Code
      ansible.builtin.import_tasks: tasks/vscode.yml
      tags: vscode
    - name: Ansible
      ansible.builtin.import_tasks: tasks/ansible.yml
      tags: ansible
