---
- name: Personal Ubuntu Environment
  hosts: localhost

  pre_tasks:
    - name: Stop if not Debian/Ubuntu
      ansible.builtin.fail:
        msg: This playbook is only for Ubuntu
      when: ansible_os_family != "Debian"

    - name: Update apt
      ansible.builtin.apt:
        update_cache: true
      become: true

  tasks:
    - name: APT
      ansible.builtin.import_tasks: tasks/apt.yml
    - name: Dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yml
    - name: ZSH
      ansible.builtin.import_tasks: tasks/zsh.yml
    - name: Python
      ansible.builtin.import_tasks: tasks/python.yml
    - name: Nodejs
      ansible.builtin.import_tasks: tasks/node.yml
    - name: Go
      ansible.builtin.import_tasks: tasks/go.yml
    - name: Rust
      ansible.builtin.import_tasks: tasks/rust.yml
    - name: Neovim
      ansible.builtin.import_tasks: tasks/neovim.yml
    - name: Ansible
      ansible.builtin.import_tasks: tasks/ansible.yml
