# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook
# yamllint enable rule:line-length
---
- name: Personal Ubuntu Environment
  hosts: localhost

  pre_tasks:
    - name: Stop if not Debian/Ubuntu
      ansible.builtin.fail:
        msg: This playbook is only for Ubuntu
      when: ansible_os_family != "Debian"
      tags: always

    - name: Update apt
      become: true
      ansible.builtin.apt:
        update_cache: true
      tags: always

    - name: Ensure Common Folders
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        mode: "755"
      loop:
        - "{{ common_bin }}"
        - "{{ common_opt }}"
      tags: always

    - name: Create Common Temporary Directory
      ansible.builtin.tempfile:
        state: directory
      register: tempdir
      tags: always

  environment:
    DEBIAN_FRONTEND: noninteractive

  vars:
    common_bin: "{{ ansible_user_dir }}/bin"
    common_opt: "{{ ansible_user_dir }}/opt"

  tasks:
    - name: APT
      ansible.builtin.import_tasks: tasks/apt.yml
      tags: apt

    - name: Git
      ansible.builtin.import_tasks: tasks/git.yml
      tags: git

    - name: Snap
      ansible.builtin.import_tasks: tasks/snap.yml
      tags: snap

    - name: Dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yml
      tags: dotfiles

    - name: ZSH
      ansible.builtin.import_tasks: tasks/zsh.yml
      tags:
        - dotfiles
        - zsh

    - name: Fonts
      ansible.builtin.import_tasks: tasks/fonts/main.yml
      tags:
        - dotfiles
        - fonts

    - name: Nodejs
      ansible.builtin.import_tasks: tasks/node.yml
      tags:
        - node
        - npm

    - name: Go
      ansible.builtin.import_tasks: tasks/go.yml
      tags: go

    - name: Rust
      ansible.builtin.import_tasks: tasks/rust.yml
      tags: rust

    - name: Java
      ansible.builtin.import_tasks: tasks/java.yml
      tags: java

    - name: Neovim
      ansible.builtin.import_tasks: tasks/neovim.yml
      tags: neovim

    - name: GNOME Desktop Environment
      ansible.builtin.import_tasks: tasks/gnome.yml
      tags: gnome

    - name: Home Directory
      ansible.builtin.import_tasks: tasks/home.yml
      tags: home

    - name: Visual Studio Code
      ansible.builtin.import_tasks: tasks/vscode.yml
      tags: vscode

    - name: Firefox
      ansible.builtin.import_tasks: tasks/firefox.yml
      tags: firefox

    - name: Python
      ansible.builtin.import_tasks: tasks/python/main.yml
      tags: python
