# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Setup PyPI Ansible
  vars:
    target_venv: "{{ python_dir }}/ansible-venv"
    python_packages:
      - ansible
      - ansible-lint

      # NOTE: Needed for community.general.dconf ansible module
      - psutil
  block:
    - name: Create Ansible virtualenv
      ansible.builtin.command:
        argv:
          - "{{ ansible_python.executable }}"
          - "{{ virtualenv_pyz }}"
          - "-p={{ python_exe }}"
          - "{{ target_venv }}"
        creates: "{{ target_venv }}/bin/python"

    - name: Install Ansible Packages
      ansible.builtin.pip:
        virtualenv: "{{ target_venv }}"
        state: latest  # noqa package-latest
        name: "{{ python_packages }}"

    - name: Link Ansible Package Binaries
      ansible.builtin.file:
        state: link
        src: "{{ item }}"
        dest: "{{ ansible_user_dir }}/bin/{{ item | basename }}"
      with_fileglob:
        - "{{ target_venv }}/bin/ansible*"

- name: Remove APT Ansible
  block:
    - name: Remove APT Ansible
      become: true
      ansible.builtin.apt:
        state: absent
        autoclean: true
        autoremove: true
        name:
          - ansible

    - name: Remove Ansible PPA
      become: true
      ansible.builtin.apt_repository:
        state: absent
        repo: ppa:ansible/ansible
