# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Setup virtualenv
  vars:
    target_venv: "{{ python_dir }}/venv"
    python_packages:
      - autopep8
      - bwenv
      - flake8
      - podman-compose
      - tldr
      - tox
      - twine
      - virtualenv
      - yamllint
  block:
    - name: Create venv virtualenv
      ansible.builtin.command:
        argv:
          - "{{ ansible_python.executable }}"
          - "{{ virtualenv_pyz }}"
          - "-p={{ python_exe }}"
          - "{{ target_venv }}"
        creates: "{{ target_venv }}/bin/python3"

    - name: Install Python Packages
      ansible.builtin.pip:
        virtualenv: "{{ target_venv }}"
        state: latest  # noqa package-latest
        name: "{{ python_packages }}"

    - name: Link Python and Pip Binaries
      ansible.builtin.file:
        state: link
        src: "{{ item }}"
        dest: "{{ common_bin }}/{{ item | basename }}"
      with_fileglob:
        - "{{ target_venv }}/bin/pip"
        - "{{ target_venv }}/bin/pip3"
        - "{{ target_venv }}/bin/pip3.*"
        - "{{ target_venv }}/bin/python"
        - "{{ target_venv }}/bin/python3"
        - "{{ target_venv }}/bin/python3.*"

    - name: Link Python Package Binaries
      ansible.builtin.file:
        state: link
        src: "{{ target_venv }}/bin/{{ item }}"
        dest: "{{ common_bin }}/{{ item }}"
      loop: "{{ python_packages }}"
