---
- name: Update All Packages
  ansible.builtin.apt:
    state: latest  # noqa package-latest
    upgrade: full
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install Packages
  ansible.builtin.apt:
    state: present
    name:
      - build-essential
      - curl
      - dos2unix
      - fzf
      - git
      - jq
      - neofetch
      - podman
      - tmux
      - tree
      - wget
      - xclip
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Cleanup apt
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    clean: true
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive
