---
- name: Setup dotfiles
  vars:
    dotfiles_dir: "{{ ansible_user_dir }}/.dotfiles"
  block:
    - name: Clone dotfiles Repo  # noqa latest[git]
      ansible.builtin.git:
        repo: git@github.com:arkinmodi/dotfiles
        dest: "{{ dotfiles_dir }}"
        recursive: true
        accept_newhostkey: true

    - name: Link zsh Configurations
      vars:
        dotfiles_zsh: "{{ dotfiles_dir }}/zsh"
      block:
        - name: Link zsh Configurations
          ansible.builtin.file:
            state: link
            src: "{{ dotfiles_zsh }}/.config/zsh"
            dest: "{{ ansible_user_dir }}/.config/zsh"

        - name: Link zsh Home Redirect Configurations
          ansible.builtin.file:
            state: link
            src: "{{ dotfiles_zsh }}/.zshenv"
            dest: "{{ ansible_user_dir }}/.zshenv"

    - name: Link git Configurations
      ansible.builtin.file:
        state: link
        src: "{{ dotfiles_dir }}/git/.config/git"
        dest: "{{ ansible_user_dir }}/.config/git"

    - name: Link Alacritty Configurations
      ansible.builtin.file:
        state: link
        src: "{{ dotfiles_dir }}/alacritty/.config/alacritty"
        dest: "{{ ansible_user_dir }}/.config/alacritty"

    - name: Link Neovim Configurations
      ansible.builtin.file:
        state: link
        src: "{{ dotfiles_dir }}/nvim/.config/nvim"
        dest: "{{ ansible_user_dir }}/.config/nvim"

    - name: Link tmux Configurations
      ansible.builtin.file:
        state: link
        src: "{{ dotfiles_dir }}/tmux/.config/tmux"
        dest: "{{ ansible_user_dir }}/.config/tmux"

    - name: Link User Scripts
      block:
        - name: Ensure bin folder
          ansible.builtin.file:
            state: directory
            path: "{{ ansible_user_dir }}/bin"
            mode: "755"

        - name: Link User Scripts
          ansible.builtin.file:
            state: link
            src: "{{ item }}"
            dest: "{{ ansible_user_dir }}/bin/{{ item | basename }}"
          with_fileglob:
            - "{{ dotfiles_dir }}/scripts/*"
