# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Download and Install Go & Purge Old Go
  when: ansible_machine == 'x86_64' or ansible_machine == 'arm64'
  vars:
    go_version: 1.21.0

    go_x86_archive_name: "go{{ go_version }}.linux-amd64"
    go_x86_sha256: d0398903a16ba2232b389fb31032ddf57cac34efda306a0eebac34f0965a0742  # yamllint disable-line rule:line-length

    go_arm_archive_name: "go{{ go_version }}.linux-arm64"
    go_arm_sha256: f3d4548edf9b22f26bbd49720350bbfe59d75b7090a1a2bff1afad8214febaf3  # yamllint disable-line rule:line-length

    go_archive_name: "{{ (ansible_machine == 'x86_64') | ternary(go_x86_archive_name, go_arm_archive_name) }}"  # yamllint disable-line rule:line-length
    go_sha256: "{{ (ansible_machine == 'x86_64') | ternary(go_x86_sha256, go_arm_sha256) }}"  # yamllint disable-line rule:line-length
    go_opt_dir: "{{ common_opt }}/go-{{ go_version }}"  # yamllint disable-line rule:line-length

    go_packages:
      - package_name: golang.org/x/tools/gopls
        binary_name: gopls
      - package_name: github.com/go-task/task/v3/cmd/task
        binary_name: task
  environment:
    GOPATH: "{{ go_opt_dir }}"
  block:
    - name: Download Go tar
      ansible.builtin.get_url:
        # https://go.dev/dl/
        url: "https://go.dev/dl/{{ go_archive_name }}.tar.gz"
        checksum: "sha256:{{ go_sha256 }}"
        dest: "/tmp/{{ go_archive_name }}.tar.gz"
        mode: "755"

    - name: Ensure opt folder
      ansible.builtin.file:
        state: directory
        path: "{{ go_opt_dir }}/{{ go_archive_name }}"
        mode: "755"

    - name: Unarchive Go tar
      ansible.builtin.unarchive:
        src: "/tmp/{{ go_archive_name }}.tar.gz"
        dest: "{{ go_opt_dir }}/{{ go_archive_name }}"
        remote_src: true
        creates: "{{ go_opt_dir }}/{{ go_archive_name }}/go/bin/go"
        mode: "755"

    - name: Link Go Binaries
      ansible.builtin.file:
        state: link
        src: "{{ item }}"
        dest: "{{ common_bin }}/{{ item | basename }}"
      with_fileglob:
        - "{{ go_opt_dir }}/{{ go_archive_name }}/go/bin/*"

    - name: Install Go Packages
      ansible.builtin.command:
        cmd: "go install {{ item.package_name }}@latest"
      register: result
      changed_when: result.stderr != ""
      loop: "{{ go_packages }}"

    - name: Link Go Package Binaries
      ansible.builtin.file:
        state: link
        src: "{{ go_opt_dir }}/bin/{{ item.binary_name }}"
        dest: "{{ common_bin }}/{{ item.binary_name }}"
      loop: "{{ go_packages }}"

    - name: Find Old Go
      ansible.builtin.find:
        paths: "{{ common_opt }}"
        pattern: "go-*"
        file_type: directory
      register: old_gos

    - name: Purge Old Go
      ansible.builtin.file:
        state: absent
        path: "{{ item.path }}"
      vars:
        paths_to_keep:
          - "{{ go_opt_dir }}"
      when: item.path not in paths_to_keep
      loop: "{{ old_gos.files }}"
