# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Purge Default Folders
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  loop:
    - "{{ ansible_user_dir }}/Documents"
    - "{{ ansible_user_dir }}/Music"
    - "{{ ansible_user_dir }}/Pictures"
    - "{{ ansible_user_dir }}/Public"
    - "{{ ansible_user_dir }}/Templates"
    - "{{ ansible_user_dir }}/Videos"
    - "{{ ansible_user_dir }}/snap"

- name: Ensure Workspace Folders
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: "755"
  loop:
    - "{{ ansible_user_dir }}/code/sandbox"
