# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Install Neovim Dependencies
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      # Build deps
      - ccache
      - cmake
      - curl
      - gettext
      - ninja-build
      - unzip

- name: Clone Neovim Repository
  ansible.builtin.git:
    accept_newhostkey: true
    depth: 1
    dest: "{{ ansible_user_dir }}/opt/neovim/repo"
    repo: git@github.com:neovim/neovim
    version: stable
  register: clone

- name: Build Neovim
  when: clone.before != clone.after
  block:
    - name: Clean Neovim Repository  # noqa: command-instead-of-module
      ansible.builtin.command: git clean -ffxd
      register: result
      changed_when: result.stdout != ""

    - name: Build & Install Neovim
      community.general.make:
        target: install
        chdir: "{{ ansible_user_dir }}/opt/neovim/repo"
        params:
          CMAKE_BUILD_TYPE: Release
          CMAKE_INSTALL_PREFIX: "{{ ansible_user_dir }}/opt/neovim/build"

- name: Link Neovim
  ansible.builtin.file:
    state: link
    src: "{{ ansible_user_dir }}/opt/neovim/build/bin/nvim"
    dest: "{{ ansible_user_dir }}/bin/nvim"

- name: Install Neovim Plugins
  ansible.builtin.command: nvim --headless '+Lazy! restore' +qa
  register: result
  changed_when: result.stderr != ""
