# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Install Neovim Dependencies
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      # Build deps
      - ccache
      - cmake
      - curl
      - gettext
      - ninja-build
      - unzip

- name: Setup Neovim
  vars:
    neovim_repo: "{{ common_opt }}/neovim/repo"
    neovim_build: "{{ common_opt }}/neovim/build"
  block:
    - name: Clone Neovim Repository
      ansible.builtin.git:
        accept_newhostkey: true
        depth: 1
        dest: "{{ neovim_repo }}"
        repo: git@github.com:neovim/neovim
        version: stable
      register: clone

    - name: Build Neovim
      when: clone.before != clone.after
      block:
        - name: Clean Neovim Repository  # noqa: command-instead-of-module
          ansible.builtin.command: git clean -ffxd
          register: result
          changed_when: result.stdout != ""

        - name: Build & Install Neovim
          community.general.make:
            target: install
            chdir: "{{ neovim_repo }}"
            params:
              CMAKE_BUILD_TYPE: Release
              CMAKE_INSTALL_PREFIX: "{{ neovim_build }}"

    - name: Link Neovim
      ansible.builtin.file:
        state: link
        src: "{{ neovim_build }}/bin/nvim"
        dest: "{{ common_bin }}/nvim"

    - name: Install Neovim Plugins
      ansible.builtin.command: nvim --headless '+Lazy! restore' +qa
      register: result
      changed_when: result.stderr != ""
