# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Install Rust
  when: ansible_machine == 'x86_64' or ansible_machine == 'arm64'
  vars:
    rust_version: 1.72.0
    rust_archive_name: "rust-{{ rust_version }}"
    rust_opt_dir: "{{ common_opt }}/{{ rust_archive_name }}"

    # https://rust-lang.github.io/rustup/installation/other.html
    rustup_x86_arch: x86_64-unknown-linux-gnu
    rustup_x86_sha256: 0b2f6c8f85a3d02fde2efc0ced4657869d73fccfce59defb4e8d29233116e6db  # yamllint disable-line rule:line-length

    rustup_arm_arch: aarch64-unknown-linux-gnu
    rustup_arm_sha256: 673e336c81c65e6b16dcdede33f4cc9ed0f08bde1dbe7a935f113605292dc800  # yamllint disable-line rule:line-length

    rustup_version: 1.26.0
    rustup_arch: "{{ (ansible_machine == 'x86_64') | ternary(rustup_x86_arch, rustup_arm_arch) }}"  # yamllint disable-line rule:line-length
    rustup_sha256: "{{ (ansible_machine == 'x86_64') | ternary(rustup_x86_sha256, rustup_arm_sha256) }}"  # yamllint disable-line rule:line-length

    rust_components:
      - rust-analyzer

    rust_packages:
      - package_name: bat
        binary_name: bat
      - package_name: fd-find
        binary_name: fd
      - package_name: onefetch
        binary_name: onefetch
      - package_name: ripgrep
        binary_name: rg
      - package_name: stylua
        binary_name: stylua
  environment:
    CARGO_HOME: "{{ rust_opt_dir }}/.cargo"
    RUSTUP_HOME: "{{ rust_opt_dir }}/.rustup"
  block:
    - name: Download rustup-init
      ansible.builtin.get_url:
        url: "https://static.rust-lang.org/rustup/archive/{{ rustup_version }}/{{ rustup_arch }}/rustup-init"  # yamllint disable-line rule:line-length
        checksum: "sha256:{{ rustup_sha256 }}"
        dest: "{{ tempdir.path }}/rustup-init"
        mode: "755"

    - name: Ensure opt folder
      ansible.builtin.file:
        state: directory
        path: "{{ rust_opt_dir }}"
        mode: "755"

    - name: Run rustup-init
      ansible.builtin.command:
        argv:
          - "{{ tempdir.path }}/rustup-init"
          - "--default-host={{ rustup_arch }}"
          - "--default-toolchain={{ rust_version }}"
          - --no-modify-path
          - --profile=default
          - -y
        creates: "{{ rust_opt_dir }}/.rustup/toolchains/{{ rust_version }}-{{ rustup_arch }}/bin/rustc"  # yamllint disable-line rule:line-length

    - name: Install Rust Components
      ansible.builtin.command:
        argv:
          - "{{ rust_opt_dir }}/.cargo/bin/rustup"
          - component
          - add
          - "{{ item }}"
      loop: "{{ rust_components }}"
      register: result
      changed_when: "'is up to date' not in result.stderr"

    - name: Link Rust Binaries
      ansible.builtin.file:
        state: link
        src: "{{ item }}"
        dest: "{{ common_bin }}/{{ item | basename }}"
      with_fileglob:
        - "{{ rust_opt_dir }}/.cargo/bin/cargo*"
        - "{{ rust_opt_dir }}/.cargo/bin/rust*"

    - name: Install Rust Packages
      community.general.cargo:
        name: "{{ rust_packages | map(attribute='package_name') }}"
        state: latest

    - name: Link Rust Package Binaries
      ansible.builtin.file:
        state: link
        src: "{{ rust_opt_dir }}/.cargo/bin/{{ item.binary_name }}"
        dest: "{{ common_bin }}/{{ item.binary_name }}"
      loop: "{{ rust_packages }}"

    - name: Find Old Rust
      ansible.builtin.find:
        paths: "{{ common_opt }}"
        pattern: "rust-*"
        file_type: directory
      register: old_rust

    - name: Purge Old Rust
      ansible.builtin.file:
        state: absent
        path: "{{ item.path }}"
      vars:
        paths_to_keep:
          - "{{ rust_opt_dir }}"
      when: item.path not in paths_to_keep
      loop: "{{ old_rust.files }}"
