# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Download Microsoft GPG Public Key
  become: true
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/packages.microsoft.asc
    checksum: sha256:2cfd20a306b2fa5e25522d78f2ef50a1f429d35fd30bd983e2ebffc2b80944fa  # yamllint disable-line rule:line-length
    mode: "755"

- name: Add Visual Studio Code Apt Repository
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb
      [arch=amd64,arm64,armhf
      signed-by=/etc/apt/keyrings/packages.microsoft.asc]
      https://packages.microsoft.com/repos/code stable main
    state: present
    filename: vscode

- name: Install Visual Studio Code
  become: true
  ansible.builtin.apt:
    name: code
    state: present
    update_cache: true
