---
- name: Install zsh
  ansible.builtin.apt:
    state: present
    name:
      - zsh
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Set zsh to the default shell
  ansible.builtin.command: "usermod --shell /bin/zsh {{ ansible_user_id }}"
  become: true
  register: result
  changed_when: "result.stdout != 'usermod: no changes'"
