# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Ensure Font
  vars:
    target_name: "{{ font.name }}-{{ font.version }}"
  block:
    - name: Download font tar
      ansible.builtin.get_url:
        url: "{{ font.url }}"
        checksum: "sha256:{{ font.sha256 }}"
        dest: "{{ tempdir.path }}/{{ target_name }}.tar.xz"
        mode: "755"

    - name: Ensure opt folder
      ansible.builtin.file:
        state: directory
        path: "{{ fonts_opt_dir }}/{{ target_name }}"
        mode: "755"

    - name: Unarchive font tar
      ansible.builtin.unarchive:
        src: "{{ tempdir.path }}/{{ target_name }}.tar.xz"
        dest: "{{ fonts_opt_dir }}/{{ target_name }}"
        remote_src: true
        creates: "{{ fonts_opt_dir }}/{{ target_name }}"
        mode: "755"

    - name: Link fonts
      ansible.builtin.file:
        state: link
        src: "{{ item }}"
        dest: "{{ fonts_local_share }}/{{ item | basename }}"
      with_fileglob:
        - "{{ fonts_opt_dir }}/{{ target_name }}/*.ttf"
