---
- name: Download font tar
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ font.version }}/{{ font.name }}.tar.xz"  # yamllint disable-line rule:line-length
    checksum: "sha256:{{ font.sha256 }}"
    dest: "/tmp/{{ font.name }}-{{ font.version }}.tar.xz"
    mode: "755"

- name: Ensure opt folder
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_user_dir }}/opt/fonts/{{ font.name }}-{{ font.version }}"
    mode: "755"

- name: Unarchive font tar
  ansible.builtin.unarchive:
    src: "/tmp/{{ font.name }}-{{ font.version }}.tar.xz"
    dest: "{{ ansible_user_dir }}/opt/fonts/{{ font.name }}-{{ font.version }}"
    remote_src: true
    creates: "{{ ansible_user_dir }}/opt/fonts/{{ font.name }}-{{ font.version }}/README.md"  # yamllint disable-line rule:line-length
    mode: "755"

- name: Link fonts
  ansible.builtin.file:
    state: link
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.local/share/fonts/{{ item | basename }}"
  with_fileglob:
    - "{{ ansible_user_dir }}/opt/fonts/{{ font.name }}-{{ font.version }}/*.ttf"  # yamllint disable-line rule:line-length
